### ISSUE TITLE
utils.sh is absent

### ISSUE THREAD

**Issue by PhantomPhreak** [exogroup/check_clickhouse#1]
Script can't start becaus of absent `utils.sh`
```
. $PROGPATH/utils.sh
```
Can you please add it to repo? Thanks

**Comment by lisuml** [comment]
`utils.sh` is available in [The official Nagios Plugins project](https://github.com/nagios-plugins/nagios-plugins) and should be installed as dependency of `check_clickhouse` nagios plugin. I'm planning to document the script together with its dependencies in the near future.

**Comment by lisuml** [comment]
It's more lack of documentation rather than a real issue.

**Comment by PhantomPhreak** [comment]
Ok, thanks for your info!
I found that script and now it works fine, thanks!

But i can't see the reason to care about one more script from another project just to define a variables
```
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4
```
I'll define it in the script for me and won't use utils.sh then
