### ISSUE TITLE
Check didn't run: ./utils.sh: No such file or directory

### ISSUE THREAD

**Issue by unix196** [exogroup/check_clickhouse#2]
Good day.
```
./check_clickhouse -h
./check_clickhouse: line 25: ./utils.sh: No such file or directory
```
May be you forgot push this file to repository? 
P.S. Usually checks in nagios doing with one file.

**Comment by lisuml** [comment]
This is duplicate of #1 

As this is recurring issue, I decided to update the script so it doesn't rely on utils.sh.
